CREATE TABLE hakjum (
LOWSCORE NUMBER(3),
HISCORE NUMBER(5,2),
GRADE VARCHAR2(3) PRIMARY KEY
);

INSERT INTO HAKJUM VALUES(0,59.99,'F');
INSERT INTO HAKJUM VALUES(60,64.99,'D0');
INSERT INTO HAKJUM VALUES(65,69.99,'D+');
INSERT INTO HAKJUM VALUES(70,74.99,'C0');
INSERT INTO HAKJUM VALUES(75,79.99,'C+');
INSERT INTO HAKJUM VALUES(80,84.99,'B0');
INSERT INTO HAKJUM VALUES(85,89.99,'B+');
INSERT INTO HAKJUM VALUES(90,94.99,'A0');
INSERT INTO HAKJUM VALUES(95,100,'A+');


CREATE TABLE student (
NO NUMBER PRIMARY KEY,
NAME VARCHAR2(21) NOT NULL,
KOR NUMBER(3) CHECK (KOR BETWEEN 0 AND 100) NOT NULL,
MATH NUMBER(3) CHECK (MATH BETWEEN 0 AND 100) NOT NULL,
ENG NUMBER(3) CHECK (ENG BETWEEN 0 AND 100) NOT NULL,
TOT NUMBER(3),
AVG NUMBER(5,2),
GRADE VARCHAR2(3) REFERENCES HAKJUM(GRADE)
);

CREATE SEQUENCE student_seq
	start with 1
	increment by 1;
	
DROP SEQUENCE student_seq;

DELETE FROM STUDENT;

SELECT * FROM STUDENT; 

-- 평균이 100점인 경우 GRADE를 구하는 쿼리문
SELECT GRADE FROM GRADE WHERE 100 BETWEEN LOWSCORE AND HISCORE;
